version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 539247488585.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t tutorial5-app .
      - docker tag tutorial5-app:latest 539247488585.dkr.ecr.sa-east-1.amazonaws.com/tutorial5-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 539247488585.dkr.ecr.sa-east-1.amazonaws.com/tutorial5-app:latest
artifacts:
  files:
    - '**/*'
